apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: hazelcast
spec:
  clusterSize: 3
  repository: 'docker.io/hazelcast/hazelcast-enterprise'
  version: '{page-latest-supported-hazelcast}-slim'
  licenseKeySecret: hazelcast-license-key
  persistence:
    baseDir: "/data/hot-restart/"  <1>
    clusterDataRecoveryPolicy: "FullRecoveryOnly"  <2>
    pvc:
      accessModes: ["ReadWriteOnce"]
      requestStorage: 20Gi  <3>
